use master;
Go 

IF OBJECT_ID (N'[dbo].[REVERTTOSNAPSHOTTHEDB]') IS NOT NULL
	DROP PROCEDURE dbo.REVERTTOSNAPSHOTTHEDB; 

Go

CREATE PROCEDURE REVERTTOSNAPSHOTTHEDB 
@DBNAME nvarchar(255) = '',
@SNAPSHOTNAME nvarchar(255) = ''
AS
DECLARE @ROLLBACKTEMPLATE nvarchar(max); 


SET @ROLLBACKTEMPLATE = 'ALTER DATABASE <DBNAME> SET SINGLE_USER WITH ROLLBACK IMMEDIATE 

RESTORE DATABASE <DBNAME> FROM 
DATABASE_SNAPSHOT = ''<SNAPSHOTNAME>''

ALTER DATABASE <DBNAME> SET MULTI_USER'


SET @ROLLBACKTEMPLATE = replace(@ROLLBACKTEMPLATE, '<DBNAME>', @DBNAME)
SET @ROLLBACKTEMPLATE = replace(@ROLLBACKTEMPLATE, '<SNAPSHOTNAME>', @SNAPSHOTNAME)

EXECUTE sp_executesql @ROLLBACKTEMPLATE; 